project:
  project_id: 'vertextutorial-429522'

data:
  file_path: 'gs://mlops_churn_bucket/Churn_Modeling_Main.csv'

bucket_uri: 'gs://mlops_churn_bucket'
artifact_folder: 'artifacts_mlops_project'
region: 'us-central1'
experiment_name: 'experiment-mlops-project'

model_type:  'xgboost' # 'random-forest'

xgboost:
  param_grid:
    n_estimators: [100, 200, 300]
    max_depth: [3, 5]
    learning_rate: [0.01, 0.1]
    gamma: [0, 0.1]
    subsample: [0.8, 1.0]
    colsample_bytree: [0.8, 1.0]
    random_state: [42]

random-forest:
  param_grid:
    n_estimators: [50, 100, 200]
    max_depth: [5, 10]
    min_samples_split: [2, 5]
    min_samples_leaf: [1, 2]
    max_features: ['sqrt', 'log2']
    bootstrap: [True]
    random_state: [42]